# Generated by cpp11: do not edit by hand

cpp_burn_sparse <- function(wkb_list, xmin, ymin, xmax, ymax, ncol, nrow) {
  .Call(`_gridburn_cpp_burn_sparse`, wkb_list, xmin, ymin, xmax, ymax, ncol, nrow)
}

cpp_gridburn_init <- function() {
  invisible(.Call(`_gridburn_cpp_gridburn_init`))
}
